version: "3.9"
services:
  api:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://poker:pokerpass@db:5432/pokerbender
    depends_on:
      - db
      - redis
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - api
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: poker
      POSTGRES_PASSWORD: pokerpass
      POSTGRES_DB: pokerbender
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
  redis:
    image: redis:7-alpine
volumes:
  db_data:
